### ISSUE TITLE
Property '$i18n' does not exist on type X

### ISSUE THREAD

**Issue by doantruongminh** [nuxt-modules/i18n#1268]
I have an issue when I create new project Nuxtjs v2.15.2 with @nuxtjs/i18n v7.0.2
I followed in the docs but this issue still happen
My tsconfig.json
```
{
  "compilerOptions": {
    "target": "ES2018",
    "module": "ESNext",
    "moduleResolution": "Node",
    "lib": ["ESNext", "ESNext.AsyncIterable", "DOM"],
    "esModuleInterop": true,
    "allowJs": true,
    "sourceMap": true,
    "strict": true,
    "noEmit": true,
    "experimentalDecorators": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./*"],
      "@/*": ["./*"]
    },
    "types": ["@nuxt/types", "@nuxtjs/axios", "@nuxtjs/i18n", "@types/node"]
  },
  "exclude": ["node_modules", ".nuxt", "dist"]
}
```

My nuxtjs.config.js:
```
export default {
  // Global page headers: https://go.nuxtjs.dev/config-head
  head: {
    title: 'bitcastle-web-app',
    htmlAttrs: {
      lang: 'en',
    },
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' },
      { name: 'format-detection', content: 'telephone=no' },
    ],
    link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }],
  },

  // Global CSS: https://go.nuxtjs.dev/config-css
  css: [],

  // Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
  plugins: [],

  // Auto import components: https://go.nuxtjs.dev/config-components
  components: true,

  // Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
  buildModules: [
    // https://go.nuxtjs.dev/typescript
    '@nuxt/typescript-build',
    // https://go.nuxtjs.dev/tailwindcss
    '@nuxtjs/tailwindcss',
  ],

  // Modules: https://go.nuxtjs.dev/config-modules
  modules: [
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',
    '@nuxtjs/i18n',
  ],

  // Axios module configuration: https://go.nuxtjs.dev/config-axios
  axios: {},
  i18n: {
    locales: [
      {
        code: 'en',
        name: 'English',
        file: 'en.js',
      },
      {
        code: 'ja',
        name: '日本語',
        file: 'ja.js',
      },
    ],
    defaultLocale: 'en',
    lazy: true,
    langDir: 'lang/',
    vueI18n: {
      fallbackLocale: 'en',
      silentFallbackWarn: true,
    },
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'lang',
      redirectOn: 'root', // recommended
    },
  },
  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {},
};
```

Can somebody support me resolve this issue? Thank you very much ❤️❤️❤️

**Comment by rchl** [comment]
Where exactly are you getting that error?

**Comment by doantruongminh** [comment]
I used this.$i18n in main layout
My layouts/main.vue
```
<template>
  <div class="relative flex flex-col w-full max-h-screen pt-20">
    <header
      class="
        absolute
        top-0
        z-10
        w-full
        h-20
        flex
        items-center
        justify-between
        px-8
      "
    >
      <h1 class="text-4xl font-bold">{{ $t('guide.header.title') }}</h1>
      <div class="flex items-center">
        <button
          v-for="locale in $i18n.locales"
          :key="locale.code"
          class="mx-2"
          :class="buttonLocaleClasses(locale.code === $i18n.locale)"
          @click.prevent.stop="$i18n.setLocale(locale.code)"
        >
          {{ locale.name }}
        </button>
      </div>
    </header>
    <div class="flex flex-col h-content overflow-auto">
      <Nuxt />
    </div>
  </div>
</template>

<script lang="ts">
export default {
  layout: 'main',
  methods: {
    buttonLocaleClasses(locale: string) {
      return { 'text-primary': locale === this.$i18n.locale };
    },
  },
};
</script>

<style scoped>
.h-content {
  max-height: calc(100vh - 5rem);
  min-height: calc(100vh - 5rem);
}
</style>
```
and my issue in here:
<img width="1115" alt="Screen Shot 2021-08-26 at 13 56 22" src="https://user-images.githubusercontent.com/88993650/130915891-1b150ea0-82c0-4b55-9be5-d59847351d06.png">

**Comment by rchl** [comment]
Looks like your whole component is not properly typed. Did you follow all instructions from https://typescript.nuxtjs.org/guide/setup ? Especially the part about creating `vue-shim.d.ts`?

**Comment by doantruongminh** [comment]
Sorry, I'm a newbie NuxtJS and I created this app with nuxt-cli.
I tried setting up your reply but this issue still happends.
My vue-shim.d.ts:
```
declare module '*.vue' {
  import Vue from 'vue';
  export default Vue;
}
```

**Comment by rchl** [comment]
I can have a look if you push your project somewhere.

Note that the first error is about missing return annotation on the `buttonLocaleClasses` method. So you should fix that first and see if that helps the second issue also.

**Comment by doantruongminh** [comment]
My project is here: https://github.com/doantruongminh/example-nuxtjs-with-tailwindcss.git
I fixed the first error but this issue still happens.
Can you make me know my mistake makes this issue? Thanks!

**Comment by rchl** [comment]
And where is you `vue-shim.d.ts` file?

**Comment by doantruongminh** [comment]
Sorry, I wrong another project. I edited the previous comment

**Comment by rchl** [comment]
Works just fine here:

![Screenshot 2021-08-26 at 10 58 33](https://user-images.githubusercontent.com/153197/130933861-518675f0-f620-4f85-9760-d17cf15f6744.png)


Make sure that you've restarted your editor.
Also you might want to add a `typescript` dependency in your project to not depend on some random version being used.

**Comment by doantruongminh** [comment]
Did you try to run command ```yarn dev```?

**Comment by rchl** [comment]
I guess you need to use `export default Vue.extend({...})` when using `lang="ts"`.

**Comment by doantruongminh** [comment]
Yes, I think it is my mistake. Thank you very much ❤️❤️❤️❤️
