### ISSUE TITLE
Hydration mismatch (server translated, client not translated)

### ISSUE THREAD

**Issue by cernymatej** [nuxt-modules/i18n#1822]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.1.0`
- Nitro Version:    `2.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.8`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-mmsybq?file=nuxt.config.ts

### Describe the bug

After a recent update, a hydration mismatch occurs. I have a copy of a project on an older version of the i18n module which works fine, however, in the newer one, the translation key flashes for a while on the client side and gets localized afterwards.
There is a hydration mismatch warning in the console as well.

```
[Vue warn]: Hydration text content mismatch in <div>:
- Client: test_message
- Server: Yes it's working 
  at <App key=2 > 
  at <NuxtRoot>
```

**Comment by sawa-ko** [comment]
Hi, use the Edge version. There it was already fixed.

**Comment by cernymatej** [comment]
Great, thanks for the info, didn't know that :)

**Comment by mostafaznv** [comment]
@nuxtjs/i18n@npm:@nuxtjs/i18n-edge@8.0.0-beta.13-28151010.d05ca82

and this issue still exists

**Comment by mostafaznv** [comment]
> @nuxtjs/i18n@npm:@nuxtjs/i18n-edge@8.0.0-beta.13-28151010.d05ca82
> 
> and this issue still exists

**Update:**
I don't know why, but npm was installing an old version of @intlify/core-base (`9.2.2`) even though I installed ^8.0.0-beta.13.
I changed it manually and it works now.

**Update:**
You can update/install nuxt-i18n to the latest version using `--legacy-peer-deps` 
```bash
npm upgrade --legacy-peer-deps
# or
npm install --legacy-peer-deps
```
