### ISSUE TITLE
When SSR is enabled, translations with `useI18n` does not work.

### ISSUE THREAD

**Issue by michael-sem** [nuxt-modules/i18n#1956]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `i18n`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.10`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-gkk2fg?file=app.vue

run `yarn bulild`
run `node .output/server/index.mjs` to serve the build

### Describe the bug

When SSR is enabled, translations with `useI18n` do not work. I got error:
`[intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format. So translate function return 'text'.`

On the page, you might see the correct translation because it is refreshed during client-side mounting. However, in the `view-source`, you will only see the translation key.

**Comment by kazupon** [comment]
Unfortunately, The `messages` options specified in `useI18n` are currently not pre-compileable at build time.
If you want to define and translate locale messages per SFC, we recommend to use i18n custom blocks.

**Comment by michael-sem** [comment]
Perhaps the solution would be to extract the 'messages' from the object passed in useI18n and transform it into JSON within the <i18n> tag? And call it in "prebuild"?

**Comment by awacode21** [comment]
> Unfortunately, The `messages` options specified in `useI18n` are currently not pre-compileable at build time. If you want to define and translate locale messages per SFC, we recommend to use i18n custom blocks.

is it planned to be provided in future, as this is a real bummer when using SSR?

**Comment by awacode21** [comment]
Related: https://github.com/nuxt/nuxt/issues/18866

**Comment by kazupon** [comment]
I belive this issue is fixed by https://github.com/nuxt-modules/i18n/pull/2199
So, you can try to install v8.0.0-rc.1 or later

**Comment by awacode21** [comment]
@kazupon ok i now tried with v8.0.0-rc.1

on `npm run dev `the issue is still appearing as described.

on 
`npm run build `
and following
`npm run preview`

the application is broken and i get the following error on node console:
```
[nuxt] [request error] [unhandled] [500] The requested module '@intlify/core-base' does not provide an export named 'compile'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```


**which let me think this is not fixed, it got worse. The issue should not be closed**


<img width="1912" alt="Bildschirmfoto 2023-08-01 um 17 15 33" src="https://github.com/nuxt-modules/i18n/assets/30939926/abffcd16-cbb5-4501-b28e-27533466cfb0">

**Comment by p-sviridov** [comment]
@kazupon i also tried v8.0.0-rc.1
on `npm run dev` the issue is still appearing.

_[intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format. So translate function return [messageName]_

**Comment by kazupon** [comment]
@awacode21 @p-sviridov 
As I mentioned again, please give us your minimal reproduction. We cannot debug without it. 🙏

**Comment by Rigo-m** [comment]
@kazupon  isn't this a reproduction for the same issue? https://github.com/nuxt-modules/i18n/issues/2111#issue-1727591935

**Comment by jojomatik** [comment]
I'm currently facing the same issue: I can see the translation keys shortly in the built version (https://nuxt.jojomatik.de/de/login).

After hydrationt hey are replaced by the correct texts. This also affects the link previews.

For me this issue is present since I updated nuxt and this package. See compare link: https://github.com/jojomatik/nuxt-3-base/compare/f162413a71b482dd4603ff07ed0fc587430a1ee5...7c9756a0fd43604191d7c8bd764789af4849fafd
