### ISSUE TITLE
Missing i18n options file with `npm run generate`

### ISSUE THREAD

**Issue by WolfgangDrescher** [nuxt-modules/i18n#1990]
### Environment

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n-edge@8.0.0-beta.11-28023078.39cf21b
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-6ylvpz

run `npm i && npm run generate && serve .output/public`

### Describe the bug

When the nuxt project is built with `npm run generate` the generated build will crash and throw error 500 with error message `format is not defined`. When you check the network tab in the developer tools you will see that the `i18n-config-[hash].js` file will not exist status 404 is returned.

<img width="1190" alt="Bildschirmfoto 2023-04-13 um 16 07 18" src="https://user-images.githubusercontent.com/865594/231784802-7e05e3d2-2ce0-48ef-9102-3d9dc3ebd334.png">

**Comment by WolfgangDrescher** [comment]
When you try to build with the old syntax

```js
export default defineNuxtConfig({
    i18n: {
        strategy: 'prefix_except_default',
        locales: [
            { code: 'de', iso: 'de-DE', file: 'de.yaml', dir: 'ltr' },
            { code: 'en', iso: 'en-US', file: 'en.yaml', dir: 'ltr' },
        ],
        defaultLocale: 'de',
        langDir: 'locales/',
        vueI18n: {
            fallbackLocale: 'de',
            legacy: false,
            locale: 'de',
        },
    },
});
```

the console will output:

```
ERROR  [@nuxtjs/i18n]: The vueI18n option is no longer be specified with object.
It must be specified in the configuration file via the 'i18n.config' path.
About deprecated reason, see https://v8.i18n.nuxtjs.org/guide/migrating#change-the-route-key-rules-in-pages-option
About new configuration style, sqee https://v8.i18n.nuxtjs.org/getting-started/basic-usage#translate-with-vue-i18n
```

However, `i18n.config` doesn't seem to exist in the module options, or am I wrong?

https://github.com/nuxt-modules/i18n/blob/a0ead8d74aadcb07067bdf517a46dc91ebf60e2c/src/types.ts#L53-L88

A clarification of the correct usage in the documentation would be useful.

**Comment by kazupon** [comment]
>It must be specified in the configuration file via the 'i18n.config' path.

Sorry, This error message is wrong.
That message mean that we need to specify like `i18n.config` path to the `vueI18n` option.

**Comment by elzodxon** [comment]
How can we resolve it?

**Comment by kazupon** [comment]
The `vueI18n` option can no longer be specified with object. Instead, you must specify a configuration file such as `i18n.config.ts` and specify the path to that configuration file in the `vueI18n` option.

you can see the docs:
- basic usage
  - https://v8.i18n.nuxtjs.org/getting-started/basic-usage#translate-with-vue-i18n
- `defineI18nConfig` composable docs:
  - https://v8.i18n.nuxtjs.org/api/composables#definei18nconfig

**Comment by WolfgangDrescher** [comment]
Still there seems to be a problem with `nuxt generate`. The config file does not end up in the build. Please check the reproduction instructions. However, I also noticed that with `nuxt build` there was also a 404 client side for this file. But the website did not crash. It looks like resolving this server side works fine, but there is something wrong client side.

**Comment by edoecohen** [comment]
This is also happening to me when I try to deploy to Vercel.

When I run `nuxt build` locally, the .nuxt/i18n folder and the config file aren't automatically generated until I refresh my browser.

Here is my .nuxt folder after running `nuxt build`:
<img width="259" alt="image" src="https://user-images.githubusercontent.com/952779/232066201-c0a23f53-05c5-4b10-b10d-6d703e6d4857.png">

And here it is again after I run the build server using `node .output/server/index.mjs` and refreshing localhost:
<img width="296" alt="image" src="https://user-images.githubusercontent.com/952779/232066746-3e8d1982-fe97-4ef0-9a82-4751979d671f.png">

But in Vercel it just crashes beforehand since it can't find the config file:
<img width="295" alt="image" src="https://user-images.githubusercontent.com/952779/232066917-f9f19eec-b18b-4ba9-a8d4-5a1fb7241a24.png">

**Comment by kkuepper** [comment]
We have the same problem. It seems to be new in beta11 since beta10 doesn't have that problem (However it has another problem).

**Comment by awacode21** [comment]
<img width="904" alt="Bildschirm­foto 2023-04-23 um 12 57 27" src="https://user-images.githubusercontent.com/30939926/233835851-4e31f424-5606-4124-a8de-202cc38d1262.png">
i think i have the same or a related error. 

When building locally, everything is fine, but building on vercel ends up with a blank page throwing that error on console

**Comment by hansemannn** [comment]
Workaround: Roll back to v8.0.0-beta.10 (which requires to revert the config file change to an object notation). Once it's fixed, the config file can be used again.

**Comment by kazupon** [comment]
I’m working on this issue.

The reason is taking a little time is because our main day job DEADLINE, is coming up at the end of this month.

Please assured that this issue is not being ignored at all and wait. 🙏

**Comment by kovai** [comment]
I had the same problem.
The secret is very simple. It was the file system permissions to write files to `.nuxt` directory, because the file `.nuxt/i18n/config-cfcb45fa.js` was created after running `node .output/server/index.mjs`.
And simply fixed by adding file write permissions to the `.nuxt` directory for the node process.

**Comment by kovai** [comment]
> This is also happening to me when I try to deploy to Vercel.
> 
> When I run `nuxt build` locally, the .nuxt/i18n folder and the config file aren't automatically generated until I refresh my browser.
> 
> Here is my .nuxt folder after running `nuxt build`: <img alt="image" width="259" src="https://user-images.githubusercontent.com/952779/232066201-c0a23f53-05c5-4b10-b10d-6d703e6d4857.png">
> 
> And here it is again after I run the build server using `node .output/server/index.mjs` and refreshing localhost: <img alt="image" width="296" src="https://user-images.githubusercontent.com/952779/232066746-3e8d1982-fe97-4ef0-9a82-4751979d671f.png">
> 
> But in Vercel it just crashes beforehand since it can't find the config file: <img alt="image" width="295" src="https://user-images.githubusercontent.com/952779/232066917-f9f19eec-b18b-4ba9-a8d4-5a1fb7241a24.png">

I had the same problem.
The secret is very simple. It was the file system permissions to write files to `.nuxt` directory, because the file `.nuxt/i18n/config-cfcb45fa.js` was created after running `node .output/server/index.mjs`.
And simply fixed by adding file write permissions to the `.nuxt` directory for the node process.

**Comment by jekuer** [comment]
Still should be seen as a workaround. Default should run out of the box without messing with those rights (imho).

**Comment by urielb** [comment]
I had this exact issue when trying to deploy the result of the "npm run generate" command.

Everything worked great on development, but after deploying the application to my production server, only an error 500 page with the message "format is not defined" would show up.

In a previous comment on this thread I saw someone talking about a missing file log on the console, and when I decided to look it up on my deploy, I've noticed that the file it was missing was in a path that wasn't supposed to exist, so it is missing from the generated files.

It turns out that the i18n.options.js file was pointing to an invalid i18n.config.js file. In my case it was like this:

`import{_ as s,J as i}from"./entry.db7f202a.js";async function c(n){const e=await s(()=>import("./i18n.config.ec968ab2.js"),[],import.meta.url).then(t=>t.default||t),o=i.isFunction(e)?await e(n):i.isObject(e)?e:{};{let t=null;try{const a="/i18n-config-aabec199.js";t=await s(()=>import(a),[],import.meta.url).then(r=>r.default||r)}catch(a){console.error(format(a.message))}return o.messages=t||{},o}}export{c as default};
`

Manually modifying the file to look like this solved the issue for me:
`import { _ as s, J as i } from "./entry.db7f202a.js"; async function c(n) { const e = await s(() => import("./i18n.config.ec968ab2.js"), [], import.meta.url).then(t => t.default || t), o = i.isFunction(e) ? await e(n) : i.isObject(e) ? e : {}; { let t = null; try { const a = "/_nuxt/i18n.config.ec968ab2.js"; t = await s(() => import(a), [], import.meta.url).then(r => r.default || r) } catch (a) { console.error(format(a.message)) } return o.messages = t || {}, o } } export { c as default };
`

After I've fixed the link to the i18n.config file, everything started working as expected.

**Comment by edoecohen** [comment]
> I’m working on this issue.
> 
> The reason is taking a little time is because our main day job DEADLINE, is coming up at the end of this month.
> 
> Please assured that this issue is not being ignored at all and wait. 🙏

@kazupon any update on the fix? or ETA? thanks!

**Comment by kazupon** [comment]
I've fixed this issue.
Please check edge channel 8.0.0-beta.11-28059008.d1499b6 version.
Thanks!

**Comment by Rakantor** [comment]
> I've fixed this issue. Please check edge channel 8.0.0-beta.11-28059008.d1499b6 version. Thanks!

I'm getting a different error now when I try to build the project with `npx nuxi generate`:

```
[4:42:41 PM]  ERROR  [nuxtjs:i18n-resource-dynamic] Plugin error - Unable to get file name for unknown file "6b5f3ecd".
[4:42:41 PM] ℹ ✓ built in 12ms
[4:42:41 PM]  ERROR  Plugin error - Unable to get file name for unknown file "6b5f3ecd".
  at error (node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
  at FileEmitter.getFileName (node_modules/rollup/dist/es/shared/node-entry.js:24128:24)
  at node_modules/@nuxtjs/i18n/dist/module.mjs:1216:50
  at Array.reduce (<anonymous>)
  at Object.generateBundle (node_modules/@nuxtjs/i18n/dist/module.mjs:1215:44)
  at node_modules/rollup/dist/es/shared/node-entry.js:24551:40
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by awacode21** [comment]
The workaround of downgrading to v8.0.0-beta.10 does not work for me. It ends up in all nuxt-link not working. Need to downgrade. to v8.0.0-beta.9

**Comment by edoecohen** [comment]
> I've fixed this issue. Please check edge channel 8.0.0-beta.11-28059008.d1499b6 version. Thanks!

@kazupon I updated to edge channel 8.0.0-beta.11-28059008.d1499b6 version.
The .nuxt/i18n folder and the config file are indeed now generated during `nuxt build` and was able to deploy on Vercel.
But am also seeing some new errors that weren't there before.

**Comment by kazupon** [comment]
> But am also seeing some new errors that weren't there before.

Could you give us your errors? 🙏

**Comment by jekuer** [comment]
With latest beta12, I get another error than before too.
See below:

```
ERROR  [nuxtjs:i18n-resource-dynamic] Plugin error - Unable to get file name for unknown file "2fbc62cc".                                                                                                                                                                 20:41:56  

ℹ ✓ built in 32ms                                                                                                                                                                                                                                                          20:41:56  

 ERROR  Plugin error - Unable to get file name for unknown file "2fbc62cc".                                                                                                                                                                                                20:41:56  

  at error (/C:/Users/XYZ/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
  at FileEmitter.getFileName (/C:/Users/XYZ/node_modules/rollup/dist/es/shared/node-entry.js:24128:24)
  at /C:/Users/XYZ/node_modules/@nuxtjs/i18n/dist/module.mjs:1216:50
  at Array.reduce (<anonymous>)
  at Object.generateBundle (/C:/Users/XYZ/node_modules/@nuxtjs/i18n/dist/module.mjs:1215:44)
  at /C:/Users/XYZ/node_modules/rollup/dist/es/shared/node-entry.js:24551:40
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

And only if I have the following in my nuxt.config.ts:
`vueI18n: './vue-i18n.options.ts',`

**Comment by tlebeitsuk** [comment]
I'm getting the same error as @jekuer using nuxt generate.

**Comment by kazupon** [comment]
Please reproduction repo or stackbliz 🙏

**Comment by Rakantor** [comment]
> Please reproduction repo or stackbliz 🙏

See here: https://stackblitz.com/edit/github-cr1uk5-mr8fcr?file=package.json
Thanks!

**Comment by kazupon** [comment]
like the similar issue #2077 
https://github.com/nuxt-modules/i18n/issues/1990#issuecomment-1546143240

**Comment by ZacxDev** [comment]
I am also facing this issue with the latest beta version (12)
Here is the relevant logs from my vercel deployment:

```
@nuxtjs/i18n Cannot find module '/var/public/__i18n__/prerender/924d8e8b.js' imported from /var/task/chunks/app/_nuxt/i18n.options-3b873373.mjs
```

**Comment by kazupon** [comment]
@Rakantor 
Sorry for my late replay.
Your reproduction is same as #2029

I fixed it with #2099, so You can try edge change version.

**Comment by Rakantor** [comment]
@kazupon
I can confirm that #2099 fixed the issue on my end and I was able to deploy my project to GitHub Pages.
Thanks for all the hard work!

**Comment by WolfgangDrescher** [comment]
When using `8.0.0-beta.12-28113576.7bc33c3` I am still experiencing the same problems as @ZacxDev in https://github.com/nuxt-modules/i18n/issues/1990#issuecomment-1556060128.

I updated the reproduction repo: https://stackblitz.com/edit/github-6ylvpz-ezzvf7

Everything works fine in development mode but when you run `npm i && npm run generate && serve .output/public` in the demo repo you will get (only relevant part copied):

```
ℹ Prerendering 4 initial routes with crawler                                    nitro 12:32:44
  ├─ / (69ms)                                                                   nitro 12:32:44
  ├─ /200.html (1ms)                                                            nitro 12:32:44
  ├─ /404.html (0ms)                                                            nitro 12:32:44

[12:32:44]  ERROR  (node:26) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use node --trace-warnings ... to show where the warning was created)


 ERROR  [nuxt] [request error] [unhandled] [500] Unexpected token 'export'            12:32:44
  at Object.compileFunction …

  ├─ /__i18n__/prerender/3e10f522.js (24ms) (Error: [500] )                     nitro 12:32:44
  ├─ /_payload.js (0ms)                                                         nitro 12:32:44
✔ You can now deploy .output/public to any static hosting!                            12:32:44
```

You will get the same result while building when you run `npm i && npm run build && node .output/server/index.mjs` and an additional error when you access the page:

```
@nuxtjs/i18n Cannot find module '/home/projects/github-6ylvpz-ezzvf7/.output/public/__i18n__/prerender/3e10f522.js' imported from /home/projects/github-6ylvpz-ezzvf7/.output/server/chunks/app/_nuxt/i18n.options-6a54e9dc.mjs
```

**Comment by FreekVR** [comment]
Getting similar errors unfortunately, on beta 12 when deployed to Vercel

```
@nuxtjs/i18n Cannot find module '/var/public/__i18n__/prerender/cfcb45fa.js' imported from /var/task/chunks/app/_nuxt/i18n.options-4604e0f1.mjs
```

When the page is pre-rendered it doesn't seem to happen - but it does error when it's not and the page is rendered through nuxt SSR.
