### ISSUE TITLE
fix: extends / layers support for `i18n.config.ts`

### ISSUE THREAD

**Issue by dargmuesli** [nuxt-modules/i18n#1992]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      modules, i18n
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.11
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-akfq2d?file=playground%2Fnuxt.config.ts

### Describe the bug

A project extending another one that uses the new `i18n.config.ts` errors as the file path is not resolved properly.

**Comment by kleinpetr** [comment]
Hi I am facing similar issue when I am trying to use `resolver` for langDir
```
  i18n: {
    lazy: true,
    strategy: 'no_prefix',
    langDir: resolve('./locales'),
    locales: [{ code: 'cs', file: 'cs.yml' }],
 }
```

### When I try to use relative path
Since I am using layers, I cannot use just `./locales` as it is described in the docs, because it seems that it resolves only the last cs.yml because the path is relative. So if I use `/layer/locales/cs.yml` with any translations here and then in the same layer try to use them. and in the project (last layer) create an empty `locales/cs.yml` it doesn't see the layer cs.yml messages.. when I check virtual files it looks like this


```ts
nuxtI18nOptions.locales = [
  Object({ code: 'cs', file: 'cs.yml', path: '/home/kleinpetr/Projects/.../apps/top-layer-app/locales/cs.yml' }),
  Object({ code: 'cs', file: 'cs.yml', path: '/home/kleinpetr/Projects/.../apps/top-layer-app/locales/cs.yml' }),
]
```

My folder structure (avoided generic files)
```
├── apps
│   └── top-layer-app
│       ├── locales (here I have just empty cs.yaml)
│       ├── nuxt.config.ts (i18n config as above)
├── layers
│   ├── components
│   │   └── test-components (in this layer I have messages and components which using them)
│   │       ├── locales
│   │       ├── nuxt.config.ts (i18n config as above)
```

So it seems that it creates two times the same path, relative path to the `.nuxt/i18n.options.mjs` I guess.

When I use `resolver` as I have to use for most other plugins, I am getting the same error which you are getting with your issue. That the import failed to resolve

**Comment by kazupon** [comment]
I've fixed this issue.
Please check edge channel 8.0.0-beta.11-28059008.d1499b6 version.
Thanks!

**Comment by dargmuesli** [comment]
Works for me! Thanks :heart:

**Comment by dargmuesli** [comment]
The build pipeline still shows some [500 errors](https://github.com/maevsi/maevsi/actions/runs/4918226248/jobs/8784294069?pr=1181#step:7:5128), ~apparently~ connected to ~https://github.com/nuxt-modules/i18n/issues/2034~ https://github.com/nuxt-modules/i18n/issues/2067. ~At least my laptop crashed while trying to check if there is a memory leak, which is a good indication :wink:~

**Comment by kleinpetr** [comment]
Where we can expect it in the stable release?

**Comment by dargmuesli** [comment]
This fix is part of beta.12
