### ISSUE TITLE
Error: Missing "./dist/runtime/composables" specifier in "@nuxtjs/i18n" package

### ISSUE THREAD

**Issue by mikhgaus** [nuxt-modules/i18n#2012]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.19.1
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  npm@8.19.3
- Builder:          vite
- User Config:      modules, i18n, pages, build, nitro, css, vite, runtimeConfig, typescript
- Runtime Modules:  (), @pinia/nuxt@0.4.8, @nuxtjs/i18n@8.0.0-beta.11
- Build Modules:    -
------------------------------

### Reproduction

Sadly, after a couple of hours of trying to reproduce the error, I could manage to do so. I hope, that you maybe can make sense out of this error and provide me some tips to reproduce the error

### Describe the bug

Error occurs after running `vitest`

### Additional context

`nuxt dev` functions perfectly, as does `nuxt build` and pretty much all the other commands.

Here is the list of packages used. 

```json
"dependencies": {
    "@pinia/nuxt": "^0.4.6",
    "axios": "^1.2.2",
    "leaflet": "^1.9.1",
    "leaflet-gesture-handling": "^1.2.2",
    "pinia": "^2.0.29",
    "vite-plugin-vuetify": "^1.0.1",
    "vuetify": "^3.1.11"
  },
  "devDependencies": {
    "@mdi/js": "^7.1.96",
    "@nuxt/test-utils": "^3.2.3",
    "@nuxtjs/eslint-config-typescript": "^12.0.0",
    "@nuxtjs/i18n": "8.0.0-beta.11",
    "@types/leaflet": "^1.9.3",
    "@types/lodash-es": "^4.17.6",
    "eslint": "^8.31.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-plugin-prettier": "^4.2.1",
    "nuxt": "3.4.1",
    "prettier": "^2.8.2",
    "sass": "^1.57.1",
    "sass-loader": "^10.4.1",
    "typescript": "^4.9.4",
    "vitest": "^0.30.1",
    "vue-tsc": "^1.2.0"
  },
```

### Logs

```shell
FAIL  tests/pages.test.ts > Test Index pages
Error: Missing "./dist/runtime/composables" specifier in "@nuxtjs/i18n" package
 ❯ e node_modules/vite/dist/node/chunks/dep-d305c21f.js:16076:25
 ❯ n node_modules/vite/dist/node/chunks/dep-d305c21f.js:16076:627
 ❯ o node_modules/vite/dist/node/chunks/dep-d305c21f.js:16076:1297
 ❯ resolveExportsOrImports node_modules/vite/dist/node/chunks/dep-d305c21f.js:23295:20
 ❯ resolveDeepImport node_modules/vite/dist/node/chunks/dep-d305c21f.js:23314:31
 ❯ tryNodeResolve node_modules/vite/dist/node/chunks/dep-d305c21f.js:23000:20
 ❯ Object.resolveId node_modules/vite/dist/node/chunks/dep-d305c21f.js:22762:28
 ❯ node_modules/rollup/dist/es/shared/node-entry.js:24407:40
 ❯ PluginDriver.hookFirstAndGetPlugin node_modules/rollup/dist/es/shared/node-entry.js:24307:28
```

**Comment by mikhgaus** [comment]
The issue is resolved. It was caused by malformed import of `defineI18nConfig`

**Comment by gbyesiltas** [comment]
> defineI18nConfig

@mikhgaus Hey, could you tell what import did you use to fix it? Thanks!

**Comment by yxw007** [comment]
I used "@nuxtjs/i18n": "^8.0.0-rc.5" version problem still exists, please how did you solve it in the end ?

> > defineI18nConfig
> 
> @mikhgaus Hey, could you tell what import did you use to fix it? Thanks!

**Comment by engelnico** [comment]
I can confirm, I'm using 8.0.0-rc.5 and after updating to nuxt 3.8.0 i get the error message

```Error: missing "./dist/runtime/composables" specifier in "@nuxtjs/i18n" package"```

i have auto import set to true. Does anybody have an idea how to solve it

**Comment by Amourade** [comment]
I was in the exact same situation and realized that it was the Nuxt update that broke some imports.
I was importing the LocaleObject type like this:

`import { LocaleObject } from '@nuxtjs/i18n/dist/runtime/composables'`

Which broke when updating Nuxt, needing me to change the import to this:

`import type { LocaleObject } from '@nuxtjs/i18n/dist/runtime/composables'`

Which makes sense. Hope this can help!
