### ISSUE TITLE
[NUXT3] Deploy to Vercel, Failed: [nuxt] [request error] [unhandled] [500] ENOENT: no such file or directory, open '/vercel/path0/.nuxt/i18n/config-cfcb45fa.js'

### ISSUE THREAD

**Issue by TangsWang** [nuxt-modules/i18n#2016]
### Environment

  "devDependencies": {
    "@nuxtjs/i18n": "^8.0.0-beta.11",
    "nuxt": "3.3.3"
  },

### Reproduction

  "devDependencies": {
    "@nuxtjs/i18n": "^8.0.0-beta.11",
    "nuxt": "3.3.3"
  },

nuxt.config.ts
  modules: ['@vueuse/nuxt', '@unocss/nuxt', '@nuxt/content', '@nuxtjs/i18n'],
  i18n: {
    vueI18n: './i18n.config.ts',
  },

i18n.config.ts:
export default defineI18nConfig(nuxt => ({
  legacy: false,
  locale: 'en',
  messages: {
...
}}))

vercel

### Describe the bug

[nuxt] [request error] [unhandled] [500] ENOENT: no such file or directory, open '/vercel/path0/.nuxt/i18n/config-cfcb45fa.js'

**Comment by dhondtlaurens** [comment]
I have the same error when deploying on AWS Lambda: 

`[nuxt] [request error] [unhandled] [500] ENOENT: no such file or directory, open '/Users/laurensdhondt/Sites/xxx/xxx/.nuxt/i18n/config-0b4859c1.js'`

Note how it refers to a path on my local machine.

**Comment by hansemannn** [comment]
Same here - deployments on Vercel (and likely other providers) fail right now:

```
[nuxt] [request error] [unhandled] [500] ENOENT: no such file or directory, open '/vercel/path0/.nuxt/i18n/config-cfcb45fa.js'
```
and
```
[nuxt] [request error] [unhandled] [500] ENOENT: no such file or directory, open '/vercel/path0/.nuxt/i18n/config-cfcb45fa.js'

[nuxt] [request error] [unhandled] [500]  (500  (/__i18n__/precompile))
  at async precompileMessages (./chunks/app/server.mjs:3122:29)  
  at async i18n_options (./chunks/app/_nuxt/i18n.options-9b43ac01.mjs:33:23)  
  at async vueI18nConfigLoader (./chunks/app/server.mjs:2765:81)  
  at async resolveNuxtI18nOptions (./chunks/app/server.mjs:2767:19)  
  at async Object.setup (./chunks/app/server.mjs:3397:116)  
  at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)  
  at async applyPlugin (./chunks/app/server.mjs:135:33)  
  at async applyPlugins (./chunks/app/server.mjs:144:5)  
  at async createNuxtAppServer (./chunks/app/server.mjs:4377:7)  
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:176:19)
[nuxt] [request error] [unhandled] [500] ENOENT: no such file or directory, open '/vercel/path0/.nuxt/i18n/config-cfcb45fa.js'
```

**Comment by kovai** [comment]
I had the same problem.
The secret is very simple. It was the file system permissions to write files to `.nuxt` directory, because the file `.nuxt/i18n/config-cfcb45fa.js` was created after running `node .output/server/index.mjs`.
And simply fixed by adding file write permissions to the `.nuxt` directory for the node process.

**Comment by TuguldurJ** [comment]
> I had the same problem.
> The secret is very simple. It was the file system permissions to write files to `.nuxt` directory, because the file `.nuxt/i18n/config-cfcb45fa.js` was created after running `node .output/server/index.mjs`.
> And simply fixed by adding file write permissions to the `.nuxt` directory for the node process.

You mean every time you build, change  permission per files manually on a server? If you are using vercel like cd/ci deployment, it cannot be possible. What is the root issue?

**Comment by kazupon** [comment]
I've fixed this issue.
Please check edge channel 8.0.0-beta.11-28059008.d1499b6 version.
Thanks!

**Comment by erunks** [comment]
> I've fixed this issue. Please check edge channel 8.0.0-beta.11-28059008.d1499b6 version. Thanks!

I updated to this most recent commit, but am still experiencing this issue with Netlify's build process. This is the error message I see in the Netlify function logs:

`
ERROR  [nuxt] [request error] [unhandled] [500] ENOENT: no such file or directory, open '/opt/build/repo/.nuxt/i18n/config-9bec0e7d.js'
`

**Comment by kazupon** [comment]
I've tried to deploy the following repository with vercel and netlify.
I could not reproduce this issue.
https://github.com/kazupon/nuxt-i18n-hosting-repro-1

vercel: https://nuxt-i18n-repro-1.vercel.app/
netlify: https://harmonious-treacle-7e0aaa.netlify.app/

Could you give us your **minimal repo** please? 🙏

**Comment by JasonLandbridge** [comment]
@kazupon I think this is related with a reproducible repo https://github.com/nuxt-modules/i18n/issues/2089
