### ISSUE TITLE
Error while trying to dynamically load/reformat locale messages using definei18nLocale and ts file

### ISSUE THREAD

**Issue by xjimdim** [nuxt-modules/i18n#2145]
### Environment

Nuxi 3.4.3
                        
RootDir: /app            
Nuxt project info:      
------------------------------
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  npm@9.5.1                                                                                                                                                                                      1:05:29 PM
- Builder:          vite
- User Config:      app, components, css, postcss, modules, i18n, runtimeConfig
- Runtime Modules:  @pinia/nuxt@0.4.9, @nuxtjs/i18n@8.0.0-beta.11, @nuxtjs/google-fonts@3.0.0, @nuxtjs/device@3.1.0, @nuxtjs/tailwindcss@6.6.6
- Build Modules:    -
------------------------------

### Reproduction

reproduction link: https://codesandbox.io/p/sandbox/loving-david-ytv9tc?file=%2Flocales%2Fel-translations.ts

It should translate the message `add_option` at the index page to 'Προσθήκη επιλογής'. Instead it doesnt and it logs the error described below.

### Describe the bug

I am trying to have all my translations in one `translation.json` file so I created a .ts file for each of my locales (el.ts and en.ts). 
In there I am trying to return a correctly formatted/reduced js object for each of the locales but with no luck.

I have wasted hours in trying to figure this out but nothing seems to work.

The way that's in the reproduction repo is probably the one that throws the fewest errors, but the main one is:
 **ERROR  Internal server error: You need to define 'export default' that will return the locale messages.**

image version in browser:
![image](https://github.com/nuxt-modules/i18n/assets/8918181/eac90318-0baf-4cb2-b435-83995167dac6)

Can someone please help?

### Additional context

I have also tried having the translations file refactored to a json one but with pretty much the same results

### Logs

```shell
ERROR  Internal server error: You need to define 'export default' that will return the locale messages.
  Plugin: vite:esbuild
  File: /project/sandbox/locales/el-translations.ts
      at generate (/project/sandbox/node_modules/@intlify/bundle-utils/lib/js.js:53:19)
      at TransformContext.esbuildPlugin.transform (file:///project/sandbox/node_modules/@intlify/unplugin-vue-i18n/lib/index.mjs:273:52)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.transform (file:///project/sandbox/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42919:30)
      at async loadAndTransform (file:///project/sandbox/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53385:29)
```

**Comment by kazupon** [comment]
Hi!
Thank you for your reporting!

This is a bug that causes nuxt i18n to transform files other than `el.ts` and `en.ts` into the directory specified in the `langDir` option.

Until this issue is fixed, a workaround is to put all executable files other than `el.ts` and `en.ts` (i.e. `el-translations.ts`, `en-translations.ts` and `translations.ts`) in the directory specified by the `langDir` option. translations.ts`) can be avoided by placing them in some directory, such as the `shared` dir, instead of defining them.

**Comment by xjimdim** [comment]
Thank you!

Leaving just the `el.ts` and `en.ts` files in the specified langDIr and moving all the other files to another directory did the trick!

Hoping this gets fixed soon  ✌️

Also HMR in these files would be nice, now every time I add a new translation I have to restart nuxt because otherwise I get error:
@nuxtjs/i18n Failed locale loading:  (431 Request Header Fields Too Large (http://localhost:3000/__nuxt_vite_node__/module/data:text/javascript;charset=utf-8,const%2520resource%2520%253D%2520%257B%250A%2520%2520%2522add%2520option%2522%253A%2520 .....)

**Comment by kazupon** [comment]
> Also HMR in these files would be nice, now every time I add a new translation I have to restart nuxt because otherwise I get error:
@nuxtjs/i18n Failed locale loading: (431 Request Header Fields Too Large

This issue has fixed in v8.0.0-beta.12 already.
You can upgrade to it!

**Comment by xjimdim** [comment]
Just upgraded! 
Indeed the error is gone, however HMR still not working.
If I change or add a translation, even though the page seems to be refreshing when I update my translations json file, the translations shown on the page are still the ones from when I run `npm run dev` and the only way of getting them right is to restart the nuxt dev server

I know it's kinda minor but it will help speed up development for sure

**Comment by kazupon** [comment]
FYI: There is already a HMR issue #2026

**Comment by codetheorist** [comment]
The original error is still a thing for me, even after upgrading to `8.0.0-rc.4`.  

The error I'm receiving is: 

> You need to define 'export default' that will return the locale messages.  

I only have one language file at present, which is `en.js` and it lives in the directory specified in the `langDir` config option, which is currently set to `lang`.  The file is a standard JS file (obviously) with one export, which is the default export and contains all of the translations.

I do feel that this issue is in fact not a problem with the `@nuxtjs/i18n` module, but instead is an issue with the `@intlify/unplugin-vue-i18n`.  I'm just investigating now and will update this issue shortly with my findings.

**Comment by codetheorist** [comment]
Have downgraded the @intlify/unplugin-vue-i18n package, the issue went away for me and everything works as normal.

**Comment by Thy3634** [comment]
The original error is still a thing for me, 8.0.0-rc.5
any update now?

**Comment by nahojj** [comment]
+1

**Comment by BobbieGoede** [comment]
@Thy3634 @nahojj 
Could you provide a minimal reproduction using the latest edge release?

**Comment by rhengles** [comment]
@codetheorist

> Have downgraded the @intlify/unplugin-vue-i18n package

Downgraded to what ?

**Edit:** I don't even have that dependency in my package.json

**Comment by codetheorist** [comment]
I should have been more clear.

I had the issue, but it seems the issue is related to the package I have mentioned rather than your own.  I had it installed alongside this package and it seems to be the culprit for this issue.

**Comment by BobbieGoede** [comment]
Closing this as this issue seems to have been resolved already, if anyone is still experiencing this issue please open a new issue with a (minimal) reproduction.

**Comment by netopolit** [comment]
@rhengles Which version of `@intlify/unplugin-vue-i18n package` did you downgrade to? Thanks

**Comment by rhengles** [comment]
@netopolit 
I never solved this, my workaround was to not use Nuxt, unfortunately

**Comment by rubebop** [comment]
My context was slightly different but I was getting the same error.
In my `vite.config.mjs` file I had to include "something" in order to make the configuration with `runtimeOnly` set to `false` work:
`export default defineConfig({
  plugins: [
    [...]
    VueI18nPlugin({
      include: "",
      runtimeOnly: false
    })
  ],
[...]
)}`

**Comment by alexander-rodin** [comment]
The problem is still not fixed

**Comment by BobbieGoede** [comment]
@alexander-rodin 
> The problem is still not fixed

Can you open a new issue and provide a minimal reproduction?

**Comment by 300code** [comment]
because you load .js , .ts so it not allow so u must use json file locales each view i think better logic for u
