### ISSUE TITLE
alwaysRedirect freezing behavior

### ISSUE THREAD

**Issue by pmnzt** [nuxt-modules/i18n#2262]
### Environment

nuxt 3.6.5 
i18n v8-beta.13

### Reproduction

https://github.com/pmnzt/nuxt-i18n-repo/tree/issue2

### Describe the bug

Relating to #2255 , i tried to set alwaysRedirect to true, it seemed to fix that issue of redirecting to the browser's default locale but now i see another issue, no matter what i change 1 - removing cookies 2 - changing the browser's preferred locale, it still redirects me back to the previous browser's locale (the first time i opened the site) after that the locale would not want to be switched.

1- no matter how many times i change the preferred browser locale and removes cookies. 
2 - if a cookie was saved on 'fr' for example Now switching to 'en' which is the defaultLocale in the config, using switchLocalePath(locale.code), does not work in this case.

3 - if the strategy is set to 'prefix' not 'prefix_except_default' , then switching to 'fr' via switchLocalePath, and switching back to 'en' does write the cookie and switch the language all times, however it still redirects to 'fr' not 'en' after reloading on site's root path, even though the cookie was been set to 'en' not 'fr' the last time.

**Comment by kazupon** [comment]
Thank you for your reporting!

I've fixed #2255 
I think this issue might be caused by #2255, so Please try to use with edge channel version.

And, Your reproduction is almost unchanged from #2255.
Please give us a reproduction that can be reliably reproduced 🙏

**Comment by pmnzt** [comment]
@kazupon 
> I've fixed #2255 I think this issue might be caused by #2255, so Please try to use with edge channel version.

Thanks, But using the edge channel did not fix #2255 for me, using the same reproduction repo.

> And, Your reproduction is almost unchanged from #2255. Please give us a reproduction that can be reliably reproduced 🙏

yes it is the same repo, but i added the branch named issue2 for this one, that has the necessary changes to reproduce this issue https://github.com/pmnzt/nuxt-i18n-repo/tree/issue2   .

**Comment by kazupon** [comment]
Thank you for your reproduction updating.

I've understood that `detectBrowserLanguage` option still has bugs.

`detectBrowserLanguage` is deeply dependent on the routing strategy, so it might take some time to stabilize.

If you want to use cookies and browser navigator language to control routing, the nuxt i18n module give some API and Nuxt API (`navigateTo`), so you can custom with using them for your use case.

- composables: https://v8.i18n.nuxtjs.org/api/composables
  - `useBrowserLocale`
  - `useCookieLocale`
- extend vue-i18n api:https://v8.i18n.nuxtjs.org/api/vue-i18n
  - `getLocaleCookie`
  - `setLocaleCookie`
  - `getBrowserLocale`
