### ISSUE TITLE
Content isn't rendering correct locale with "wait for global transition" setup. 

### ISSUE THREAD

**Issue by OwenAdsit** [nuxt-modules/i18n#2269]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.14.2
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.5.0
- Builder:          vite
- User Config:      devtools, modules, css, app, i18n, prismic, postcss, device, nitro
- Runtime Modules:  @nuxtjs/prismic@3.0.0, @nuxtjs/i18n@8.0.0-beta.12, @nuxtjs/device@3.1.0
- Build Modules:    -
------------------------------

Context: 
- Prismic CMS
- Gsap in page transition hooks.

### Reproduction

[https://lang-switch--funny-unicorn-dcc38d.netlify.app/](url)

### Describe the bug

Lang Switcher:
```<template>
  <nav>
    <ul>
      <li v-for="l in availableLocales" :key="`langSwitcher--${l}`">
        <nuxt-link :to="switchLocalePath(l)">{{ l }}</nuxt-link>
      </li>
    </ul>
  </nav>
</template>

<script setup>
const { locale, locales } = useI18n();
const switchLocalePath = useSwitchLocalePath();

const availableLocales = computed(() => {
  return locales.value.filter((i) => i !== locale.value);
});
</script>
```
Data Fetching: 
```
<template>
  <div class="space-y-56">
    <SliceZone :components="components" :slices="page.data.slices" />
  </div>
</template>

<script setup>
import { components } from "~/slices";
const { client } = usePrismic();
const { locale } = useI18n();
const { data: page } = await useAsyncData("homepage", async () => {
  const document = await client.getSingle("home", { lang: locale.value });
  if (document) {
    return document;
  } else {
    throw createError({ statusCode: 404, message: "Page not found" });
  }
});
</script>
```
App.vue
```
<template>
  <Html :class="darkMode ? 'dark' : 'light'" :lang="locale">
    <div>
      <the-mouse-layer v-if="!touch" />
      <TheTransitionLayer />
      <NuxtLayout>
        <NuxtPage
          :transition="{
            ...usePageTransition(),
            onBeforeEnter,
          }"
        />
      </NuxtLayout>
    </div>
    <div
      class="fixed top-0 bg-overlay opacity-40 w-screen h-screen pointer-events-none"
    ></div>
  </Html>
</template>

<script setup>
const { locale } = useI18n();
const { darkMode } = useDark();
const { touch } = useTouch();
const { initScroll } = useScroll();
onMounted(() => {
  initScroll();
});

const { finalizePendingLocaleChange } = useI18n();
const onBeforeEnter = async () => {
  console.log(finalizePendingLocaleChange);
  await finalizePendingLocaleChange();
};
</script>
```

### Additional context

Things I've tried to fix:
1. Initially i had ```<NuxtPage :page-key="route => route.fullPath" />``` but the change in locale in onBeforeEnter() would trigger another transition.
2.  Adding keys to my individual components. => Page transition would be triggered but the content wouldn't change.
3. Unique keys according to locale in useAsyncData() => Same as above.
4. Listening to i18n:langSwitch hook and calling refreshNuxtData() => correct  locale, but prismic slices rendered all out of order.

Perhaps I using nuxt/i18n completely wrong. Please let me know. Appreciate the help.

**Comment by kazupon** [comment]
Thank you for your reporting!

I also checked the reproduced APP hosted on your netlify.
It seem that does not appear to be working correctly. 🤔 
From the your put codes, it appears to be set up as documented.

To debug, we need your minimal reproduction code to run local to our implementation.
could you give it to us please ? 🙏

**Comment by OwenAdsit** [comment]
Great ill have the reproduction up by the end of the day. Thanks

**Comment by kazupon** [comment]
Hi!

global transition had bug.
so, I've fixed it and I released v8.0.0-rc.2
Please check it!

**Comment by OwenAdsit** [comment]
Unfortunately the new release i updated didn't fix the issue. Thank you for your update though. 

I suspect is is caused by the AsyncData & Mounted hooks being called before the beforeEnter, and other transition hooks. For the rendering page.  I could be wrong.

[Reproduction](https://github.com/OwenAdsit/prismic-i18n-reproduction)
[In a Live Setting](https://lang-switch--funny-unicorn-dcc38d.netlify.app/)

**Comment by kazupon** [comment]
Thank you for your reproduction!

In the meantime other issues have come in. I will check your reproduction once I see all those issue triages!

**Comment by BobbieGoede** [comment]
I think this issue is related to the use of `useAsyncData` in combination with transitions, the Nuxt docs mentions this in the known issues sections [here](https://nuxt.com/docs/getting-started/transitions#known-issues).

After playing around with your reproduction I may have a workaround, you can find it [here](https://stackblitz.com/edit/github-hqv2p4?file=app.vue,pages%2Findex.vue,nuxt.config.ts). To find out what went wrong I also added the translations as files, but those changes can be ignored. 

Adding `{ watch: [locale] }` as options to the `useAsyncData` call seems to solve the issue of not rendering the correct locale. Unfortunately it looks like the page is mounted on every transition, so it will trigger the `useAsynData` twice, once during transition and once after locale has been switched.

**Comment by Triloworld** [comment]
Nuxt Version: 3.5.3 
Try updating Nuxt version. It is fixed in Vue core :) https://github.com/vuejs/core/issues/5844
Landed in latest version in Nuxt.

**Comment by BobbieGoede** [comment]
Unfortunately I can't access the reproduction anymore, so I'm unable to confirm whether this was fixed in Vue core as mentioned. I hope it has been resolved for you by updating to the latest Nuxt version. I'll close this issue for now, if you're still experiencing this issue let me know (with a reproduction!) and I will reopen it 😄.
