### ISSUE TITLE
does not redirect to the saved locale

### ISSUE THREAD

**Issue by pmnzt** [nuxt-modules/i18n#2277]
### Environment

nuxt 3.6.5
i18n v8.beta.13 | npm:@nuxtjs/i18n-edge

### Reproduction

https://github.com/pmnzt/nuxt-i18n-repo

### Describe the bug

the cookie is set to fr

opening the site does not redirect to 'fr' 

switching the lang is done using
```js
<NuxtLink  v-for="locale in availableLocales" :key="locale.code" :to="switchLocalePath(locale.code)">{{
    locale.name
  }}</NuxtLink>
```

Can be found in pages\index.vue

**Comment by kazupon** [comment]
Hi!
I believe this issue was fixed in #2276.

Your edge version maybe out of date in the package manager cache.
Here is the list of edge versions for nuxt i18n.
https://www.npmjs.com/package/@nuxtjs/i18n-edge

Could you try the latest version? 🙏

**Comment by sync42johnny** [comment]
Just wanted to report that I'm still experiencing the same issue with "@nuxtjs/i18n" version "^8.0.0-rc.1". I've tried updating and reinstalling, but the problem persists.

**Comment by kazupon** [comment]
@iboretskyi 

> Just wanted to report that I'm still experiencing the same issue with "@nuxtjs/i18n" version "^8.0.0-rc.1". I've tried updating and reinstalling, but the problem persists.

Could you give your **minimal reproduction** please?

Unless we can get a reproduction that anyone can see, we cannot go throght for good situation. We are efforting to solve the issue, but comments alone are not enough to move us forward.

**Comment by RomanSkrypnik** [comment]
> @iboretskyi
> 
> > Just wanted to report that I'm still experiencing the same issue with "@nuxtjs/i18n" version "^8.0.0-rc.1". I've tried updating and reinstalling, but the problem persists.
> 
> Could you give your **minimal reproduction** please?
> 
> Unless we can get a reproduction that anyone can see, we cannot go throght for good situation. We are efforting to solve the issue, but comments alone are not enough to move us forward.

Facing the same issue, here is my repro:
https://monosnap.com/direct/8NeUhLLU1XtxqzerD6W8sc1NoRgGik
https://github.com/RomanSkrypnik/nuxt-test-app

**Comment by kazupon** [comment]
@RomanSkrypnik 
Thank you for your reproduction!

I'm about to take a little vacation so it may take me some time to check and correct.

**Comment by franzus5** [comment]
@kazupon hi there! Faced the same issue like guys mentioned

> > @iboretskyi
> > > Just wanted to report that I'm still experiencing the same issue with "@nuxtjs/i18n" version "^8.0.0-rc.1". I've tried updating and reinstalling, but the problem persists.
> > 
> > 
> > Could you give your **minimal reproduction** please?
> > Unless we can get a reproduction that anyone can see, we cannot go throght for good situation. We are efforting to solve the issue, but comments alone are not enough to move us forward.
> 
> Facing the same issue, here is my repro: https://monosnap.com/direct/8NeUhLLU1XtxqzerD6W8sc1NoRgGik https://github.com/RomanSkrypnik/nuxt-test-app

**Comment by RomanSkrypnik** [comment]
Any updates?

**Comment by sync42johnny** [comment]
@kazupon Have there been any changes?

**Comment by martinszeltins** [comment]
Looks like it has been fixed? Seems to be working for me (latest edge channel version)

**Comment by BobbieGoede** [comment]
Closing this as I'm unable to replicate this issue using the latest version, let me know if you're still experiencing this issue (with an updated minimal reproduction)!
