### ISSUE TITLE
Cannot read properties of undefined (reading 't')

### ISSUE THREAD

**Issue by alexmercier25** [nuxt-modules/i18n#2390]
### Environment

Only on vercel

my local specs, if needed:
------------------------------
- Operating System: Darwin
- Node Version:     v18.17.1
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  yarn@1.22.15
- Builder:          -
- User Config:      app, css, build, graphqlServer, modules, security, apollo, ssr, appConfig, experimental, alias, pwa
- Runtime Modules:  @nuxtjs/google-fonts@3.0.2, @nuxtjs/i18n@8.0.0-rc.4, nuxt-graphql-server@1.2.2, @nuxtjs/apollo@5.0.0-alpha.6, nuxt-security@0.13.1, @vite-pwa/nuxt@0.1.0
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/alexmercier25/t-error

### Describe the bug

just try to deploy it on vercel, it will build but you will get a 500 error

### Logs

```shell
Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: Cannot read properties of undefined (reading 't')","reason":{"errorType":"TypeError","errorMessage":"Cannot read properties of undefined (reading 't')","stack":["TypeError: Cannot read properties of undefined (reading 't')","    at formatParts (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:823:15)","    at msg (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:818:26)","    at evaluateMessage (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:1265:22)","    at translate (file:///var/task/node_modules/@intlify/core-base/dist/core-base.mjs:1087:22)","    at file:///var/task/chunks/app/server.mjs:1404:46","    at wrapWithDeps (file:///var/task/chunks/app/server.mjs:1388:13)","    at Proxy.t (file:///var/task/chunks/app/server.mjs:1404:12)","    at _sfc_ssrRender (file:///var/task/chunks/app/_nuxt/index-a5016d3c.mjs:25:66)","    at renderComponentSubTree (/var/task/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:423:9)","    at renderComponentVNode (/var/task/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:371:12)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: Cannot read properties of undefined (reading 't')","    at process.<anonymous> (file:///var/runtime/index.mjs:1250:17)","    at process.emit (node:events:526:35)","    at emit (node:internal/process/promises:149:20)","    at processPromiseRejections (node:internal/process/promises:283:27)","    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}
Unknown application error occurred
Runtime.Unknown
```

**Comment by kazupon** [comment]
Thank you for your reporting!

This issue was fixed with https://github.com/nuxt-modules/i18n/pull/2387
if you would like to use, you can use the edge channel version.

Thanks!

**Comment by RebeccaStevens** [comment]
I had/have? the same issue. The edge channel fixes things locally for me but it's still failing in the ci. I have no idea why this may be the case.

**Comment by Saquith** [comment]
We're having the same issue when running `nuxt generate`, not build or running locally.

**Comment by mercs600** [comment]
We encounter the same issue, but only on CI - only on SSR request - it works fine on Client Side cycle 
It cannot be reproduced in a locally built environment. 
This works exclusively with edge versions, but how reliable are they for production use? 
For those considering it, please specify the edge version as 
`"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge@8.0.0-rc.4-28251471.09ead69"`
  If you intend to use this in production, ensure you don't leave it unspecified. 

Downgrading isn't an option for us; it seems the previous version is incompatible with 3.7.3.

**Comment by maximilliangeorge** [comment]
I see the same error when using an external `i18n.config.ts`. Configuration inside `nuxt.config.ts` seems to work.

**Comment by shiny** [comment]
It also happens to me. Switch to `i18n-edge` channel works, even in bun.
### How to switch
Replace `next` to `npm:@nuxtjs/i18n-edge` in package.json
```json
"@nuxtjs/i18n": "npm:@nuxtjs/i18n-edge"
```
