### ISSUE TITLE
How to use localePath() with route params?

### ISSUE THREAD

**Issue by MickL** [nuxt-modules/i18n#3004]
Unfortunately the docs doesnt show how to use `localePath()` with route params. E.g.:

```
/products/[id]
```

How to do link to such a page? I tried `localePath('products/' + id)` with no success.

EDIT: See [my answer below](https://github.com/nuxt-modules/i18n/issues/3004#issuecomment-2692410269) for full explanation

**Comment by steffenstolze** [comment]
```<NuxtLink :to="`${localePath('products')}/${item.global_name}`" v-for="item of products">  .... ```

for a URL like `https://mywebshop.com/en/products/macbook-pro-14`

and a Nuxt folder structure like

<img width="159" alt="image" src="https://github.com/nuxt-modules/i18n/assets/8490779/e1010230-637f-4f1c-8d1e-70f61f5f825d">

i18n config in nuxt.config.ts like

```
	i18n: {
		locales: [
			{
				code: 'de',
				iso: 'de-DE',
				name: 'Deutsch',
			},
			{ code: 'en', iso: 'en-GB', name: 'English' },
		],
		strategy: 'prefix',
		defaultLocale: 'de',
		customRoutes: 'config',
		rootRedirect: 'de',
		pages: {
			index: { de: '/', en: '/' },
			'products/index': { de: '/produkte', en: '/products' },
			'products/[id]': { de: '/produkte/[id]', en: '/products/[id]' },
		},
		detectBrowserLanguage: {
			useCookie: true,
			cookieKey: 'i18n_redirected',
			redirectOn: 'root',
			fallbackLocale: 'de',
		},
	},
```

**Comment by BobbieGoede** [comment]
We should document this better, my recommendation would be to use an object with the route name `localePath({ name: 'route-name', params: { id: 123 } })` (this should work with all configurations).

I think passing paths works with certain configurations but as you have noticed it won't when using `'prefix'` strategy (this is technically difficult while supporting localized paths and disabled localized paths). I'm sure we'll have that working at some point but for now we should document the most reliable method 😄

**Comment by MickL** [comment]
I always try to avoid using route names because they are hard to find and sometimes I just cant find the right one at all

**Comment by BobbieGoede** [comment]
I agree they're a bit hidden, I used to check devtools often to make sure I had the correct route name. But currently it's the most reliable way to retrieve routes regardless of i18n configuration, as the route name remains (essentially) the same across languages while the route path does not due to localization, prefix strategy, parameters and encoding.

You can also set a custom route name using `definePageMeta({ name: 'my-route' })` if you prefer, this should work as long as Nuxt's `experimental.scanPageMeta` is enabled.

**Comment by MickL** [comment]
I use custom route paths per language, e.g. `/products` becomes `/produkte` in German. Now I want to link to `/products/123` and the dev tools show me as the name `products-id___de` but that cant be right?

This is why I tried to avoid path names, but in this case I have to use them. How can I use them with custom route paths? E.g. I have the following file structure:

```
/products/index.vue
/products/[id].vue
```

Which I map to:

```
/products
/products/123
/produkte
/produkte/123
```

**Comment by MickL** [comment]
I think I got it:

```
localePath({ name: 'products-id', params: { id: props.id } })
```

**Comment by BobbieGoede** [comment]
I have just published the first release candidate for v9 which includes the experimental typed routes [`experimental.typedPages`](https://i18n.nuxtjs.org/docs/v9/options/misc#experimental), I feel like this should resolve your issue as it provides proper name autocompletion.

Try it out and please open new issues if you experience any with this feature 🙏

**Comment by MickL** [comment]
Sounds amazing, I will check soon!!

**Comment by MickL** [comment]
I tried it and it is super cool, finally autocompletion for route paths!! :)

However @BobbieGoede I would add at least one example with `name` and `params` to the docs, it is still missing. E.g. for path `app/pages/products/[id].vue`:

```
localePath({ name: 'products-id', params: { id: props.id } })
```

**Comment by BobbieGoede** [comment]
Thanks for trying it out! I agree we still need to add that somewhere in the docs, just not sure where 😂 Feel free to open a PR, reopening this issue to track the documentation issue.

**Comment by MickL** [comment]
So what I do to translate routes:

1. I define them in my pages, this way it is more organized. Before we had file-based routing, now we have in the component itself. E.g. I if have the file `products/[id].vue`:


```vue
<template>
   defineI18nRoute({
     paths: {
       de: '/produkte/[id]',
       en: '/products/[id]',
     },
   });
</template>
```

As of now, this requires in nuxt config:

```ts
experimental: {
    inlineRouteRules: true,
    scanPageMeta: true,
    typedPages: true,
  },
```

2. Then I only use named links. The name normally is the filepath, if unsure it can be seen in the devtools:

```html
<NuxtLinkLocale :to={ name: 'products-id', params: { id: '123' } }">My Link</NuxtLinkLocale>
```

This might be made a bit more clear in the docs.

A whole new problem is it tho, if the route-param itself needs to be translated. E.g. `products/[category].vue` where category is a translated string but needs to be mapped to an enum to make an api request. Discussion about that: #3028
