### ISSUE TITLE
Dependency mismatch in `v9.0.0-rc.1`

### ISSUE THREAD

**Issue by shrpne** [nuxt-modules/i18n#3152]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.17.0`
- Nuxt Version:     `3.13.2`
- CLI Version:      `3.14.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `npm@10.8.2`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

On the local environment and on the stackblitz I have different errors, but both envs not working for me

On stackblitz I have `Pre-transform error: compiler is null (x2)`
https://stackblitz.com/edit/bobbiegoede-nuxt-i18n-starter-rt9kda?file=i18n%2Fi18n.config.ts

On the local I have
```
 [ERROR] No matching export in "node_modules/@intlify/shared/dist/shared.mjs" for import "incrementer"

    node_modules/@intlify/core-base/dist/core-base.mjs:6:121:
      6 │ ...mber, isPlainObject, assign, join, toDisplayString, isArray, incrementer, format as format$1, isPromise, isBoolean, warn, isRegExp, ...
        ╵                                                                 ~~~~~~~~~~~


 ERROR  error while updating dependencies:                                                                                             11:05:53 AM
Error: Build failed with 1 error:
node_modules/@intlify/core-base/dist/core-base.mjs:6:121: ERROR: No matching export in "node_modules/@intlify/shared/dist/shared.mjs" for import "incremented"

```

### Describe the bug

v9 rc1 not run

### Additional context

`npm list @intlify/shared` gives

```
└─┬ @nuxtjs/i18n@9.0.0-rc.1
  ├─┬ @intlify/h3@0.5.0
  │ └─┬ @intlify/core@9.14.1
  │   ├─┬ @intlify/core-base@9.14.1
  │   │ └── @intlify/shared@9.14.1
  │   └── @intlify/shared@9.14.1
  ├── @intlify/shared@10.0.3
  ├─┬ @intlify/unplugin-vue-i18n@5.2.0
  │ ├─┬ @intlify/bundle-utils@9.0.0-beta.0
  │ │ ├─┬ @intlify/message-compiler@9.14.1
  │ │ │ └── @intlify/shared@9.14.1
  │ │ └── @intlify/shared@10.0.3 deduped
  │ ├── @intlify/shared@10.0.3 deduped
  │ └─┬ @intlify/vue-i18n-extensions@7.0.0
  │   └── @intlify/shared@10.0.3 deduped
  └─┬ vue-i18n@10.0.3
    ├─┬ @intlify/core-base@10.0.3
    │ ├─┬ @intlify/message-compiler@10.0.3
    │ │ └── @intlify/shared@10.0.3 deduped
    │ └── @intlify/shared@10.0.3 deduped
    └── @intlify/shared@10.0.3 deduped
```

probably the issue with intlify/h3 which requires intlify/shared@9

**Comment by BobbieGoede** [comment]
Thanks for reporting this issue, you're right it looks like we need to update deps in `@intlify/h3` and publish a release.

In the meantime I think you can work around this issue by adding the following resolutions override to your `package.json`. You may need to refresh lockfiles for this to take effect.

```
	"resolutions": {
		"@intlify/core": "^10"
	},
```

**Comment by shrpne** [comment]
I managed to pin versions on npm with
```
  "overrides": {
    "@intlify/h3": {
      "@intlify/core": "^10"
    },
    "@intlify/bundle-utils": {
      "@intlify/message-compiler": "^10"
    }
  }
```

**Comment by BobbieGoede** [comment]
Ah sorry, `resolutions` is specific to `pnpm`, just setting the one override seems to be sufficient in my testing.

```
  "overrides": {
    "@intlify/h3": {
      "@intlify/core-base": "^10.0.3"
    }
  },
```

This issue should get resolved once https://github.com/intlify/h3/pull/35 is merged, released (and updated in this module).

**Comment by gokhantaskan** [comment]
I'm getting a similar error:

```
✘ [ERROR] No matching export in "node_modules/.pnpm/@intlify+shared@10.0.4/node_modules/@intlify/shared/dist/shared.mjs" for import "create"

    node_modules/.pnpm/@intlify+core-base@10.0.5/node_modules/@intlify/core-base/dist/core-base.mjs:6:42:
      6 │ import { getGlobalThis, hasOwn, isNumber, create, isObject, isString, isBoolean, warn, format as format$1, isFunction, ...

...

ERROR  [nuxt] [request error] [unhandled] [500] __vite_ssr_import_0__.create is not a function
```

My packages:
```
"@nuxtjs/i18n": "9.0.0-rc.2" => also tried "9.1.0"
"nuxt": "^3.14.1592"
```
Node.js version v20.18.1, pnpm version 9.12.3

I also tried to add the following to package.json:
```
"resolutions": {
    "@intlify/core": "^10"
  },
```

**Comment by 7Koston** [comment]
@gokhantaskan Same. Have you managed to solve it?
upd.
```json
  "pnpm": {
    "overrides": {
      "@intlify/core": "^10.0.5",
      "@intlify/core-base": "^10.0.5",
      "@intlify/shared": "^10.0.5",
      "@intlify/message-compiler": "^10.0.5"
    }
  }
```
Worked for me.

**Comment by BobbieGoede** [comment]
@gokhantaskan @7Koston 

This issue should be resolved now as well, it was caused by a release having an incorrect tag, try refreshing your lockfiles and installing 🙏

Related https://github.com/intlify/vue-i18n/issues/2037#issuecomment-2507490733

**Comment by hymair** [comment]
@BobbieGoede I refreshed the lockfile, have all latest versions of all packages and still get this error.

```
"devDependencies": {
    "@nuxtjs/i18n": "^9.1.1",
    "nuxt": "^3.14.1592"
}
```

**Comment by BobbieGoede** [comment]
@hymair 
Could you provide a minimal reproduction? 🙏

**Comment by hymair** [comment]
I guess it's the eslint plugin? Output of `pnpm why @intlify/core-base -r`:

```
devDependencies:
@intlify/eslint-plugin-vue-i18n 3.2.0
└── @intlify/core-base 9.14.2
```

EDIT: Uninstalling and installing the eslint plugin again fixed the error.
