### ISSUE TITLE
Sourcemaps not loading with Nuxt i18n module 9.0.0

### ISSUE THREAD

**Issue by dantuv90** [nuxt-modules/i18n#3239]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.18.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      default
- Runtime Modules:  @nuxtjs/i18n@9.0.0
- Build Modules:    -
------------------------------

### Reproduction

Steps to reproduce:

Install and configure the Nuxt i18n module with version 9.0.0.
Run the Nuxt project in development mode (npm run dev or yarn dev).
Open the browser DevTools and attempt to debug the Nuxt i18n code.
Sourcemaps are not loaded, and the original source code is not available for debugging.

### Describe the bug

Since upgrading to version 9.0.0 of the Nuxt i18n module, sourcemaps are no longer being loaded, preventing me from debugging the code in the browser. This issue makes it difficult to trace and debug the source code using browser DevTools.

![Image](https://github.com/user-attachments/assets/7364107c-f7ae-405e-b800-eaa02a15aa39)

### Logs

```shell

```

**Comment by InjustFr** [comment]
I'm also facing this same issue 

Here's is a reproduction https://codesandbox.io/p/devbox/funny-rgb-hj2thz?workspaceId=649ba03f-26ca-46d1-89e9-81b5aa2c40d0

As you can see in .output/public/_nuxt, all the sourcemaps are invalid as they don't present any value in sources and mappings are empty

**Comment by yeonjulee1005** [comment]
Me too, 
I use Nuxt4 like this
```
future: {
    compatibilityVersion: 4,
  },
```

It' work fine at `v9.0.0-rc.2`

so, I rollback module version  @nuxtjs/i18n  `v9.0.0-rc.2`

**Comment by marcelobotega** [comment]
I think we may also be facing the same issue. 
Check this [issue](https://github.com/nuxt/nuxt/issues/29143) for a reproduction of the problem, could be related to the module.
This [issue](https://github.com/getsentry/sentry-javascript/issues/14247) also mentions that the module on version 9 is the problem.

**Comment by TheDutchCoder** [comment]
This is also an issue with (unit) testing. I'm not even sure why i18n is involved at all.
We're doing pure unit tests on TS util files, there's no Nuxt instance involved (well... there _shouldn't_ be, but there is, for some reason).

All our coverage results point to some intermediary processed files, not the original TS files. If I disable the nuxt-i18n module, everything works fine.

To clarify: i18n has _always_ been the reason our sourcemaps don't work properly. We also can't run local debugging in the IDE because of it.

**Comment by fornazaric** [comment]
Same issue here, a downgrade to i18n v9 and Nuxt i18n to v8 did the trick, i really don't know how they can make them break so often (talking about vue i18n, last time it was my problem too)

**Comment by BobbieGoede** [comment]
Can someone provide a new reproduction? the previous reproduction is no longer available..

The reproduction referenced by @marcelobotega does not include this module, I'll see if I can modify it to reproduce the issue but a new one would be preferred. 

The only change that comes to mind that could possibly be the source of this issue is https://github.com/intlify/bundle-tools/pull/413 (/cc @userquin). Can someone check if disabling [`bundle.optimizeTranslationDirective`](https://i18n.nuxtjs.org/docs/api/options#optimizetranslationdirective) resolves this issue? As that should prevent the changes in that PR from being executed.

**Comment by TheDutchCoder** [comment]
@BobbieGoede setting that that has no effect for us.
Only when I fully disable the module do the sourcemaps match again.

**Comment by BobbieGoede** [comment]
We may have narrowed down the issue to a version resolution conflict, can someone confirm if adding the following override to `package.json` resolves the issue?

```
  "overrides": {
    "@intlify/shared": "10.0.5"
  },
```

**Comment by jakubkoje** [comment]
> We may have narrowed down the issue to a version resolution conflict, can someone confirm if adding the following override to `package.json` resolves the issue?
> 
> ```
>   "overrides": {
>     "@intlify/shared": "10.0.5"
>   },
> ```

This doesnt fix the issue for me.

**Comment by BobbieGoede** [comment]
Can someone provide a minimal reproduction? A stackblitz project or a github repo will do.

**Comment by userquin** [comment]
> > We may have narrowed down the issue to a version resolution conflict, can someone confirm if adding the following override to `package.json` resolves the issue?
> > ```
> >   "overrides": {
> >     "@intlify/shared": "10.0.5"
> >   },
> > ```
> 
> This doesnt fix the issue for me.

If using pnpm try using `pnpm.overrides`

**Comment by jakubkoje** [comment]
> > > We may have narrowed down the issue to a version resolution conflict, can someone confirm if adding the following override to `package.json` resolves the issue?
> > > ```
> > >   "overrides": {
> > >     "@intlify/shared": "10.0.5"
> > >   },
> > > ```
> > 
> > 
> > This doesnt fix the issue for me.
> 
> If using pnpm try using `pnpm.overrides`

I am using pnpm workspace, with this override in root package.json.

```
  "pnpm": {
    "overrides": {
      "@intlify/shared": "10.0.5"
    }
  }
```

I have verified that the only installed version of `@intlify/shared` is `10.0.5`, instead of `11.0.0-rc.1` that it was before the override.

**Comment by TheDutchCoder** [comment]
We're on 10.0.4 anyway, but even with the override our sourcemaps in tests are still wrong.

**Comment by TheDutchCoder** [comment]
I'm setting up a repro with a bare setup with unit tests that have faulty sourcemaps. Give me a minute.

@BobbieGoede [here's the repro](https://github.com/TheDutchCoder/i18n-sourcemaps-bug), see the README for instructions on what to do.

Sorry for the odd "project", it's basically our enterprise app with everything removed except some utils.

**Comment by BobbieGoede** [comment]
@TheDutchCoder 
If I add the following config to `nuxt.config.ts` in your reproduction it does print the desired output described in the readme 🤔 Can you confirm you're getting the same output with the reproduction and this added config?

```
  i18n: {
    bundle: {
      optimizeTranslationDirective: false,
    },
  },
```

**Comment by userquin** [comment]
Using latest `unplugin-vue-i18n` plugin (no need to disable the directives plugin):

![Image](https://github.com/user-attachments/assets/de379212-f35f-4d07-a483-9075e261ced5)

**Comment by TheDutchCoder** [comment]
> [@TheDutchCoder](https://github.com/TheDutchCoder) If I add the following config to `nuxt.config.ts` in your reproduction it does print the desired output described in the readme 🤔 Can you confirm you're getting the same output with the reproduction and this added config?
> 
> ```
>   i18n: {
>     bundle: {
>       optimizeTranslationDirective: false,
>     },
>   },
> ```

Yes, that works in my reproduction!
Let me also check our actual project and see if it does the same.

Interestingly: it's not even an option in the other project. I assume it's a minor version behind (9.1.0), let me upgrade and see if that works.

🙌 success! On 9.1.1 with that setting it indeed maps correctly again!

**Comment by userquin** [comment]
how about using latest unplugin version without that flag disabled?

**Comment by TheDutchCoder** [comment]
> how about using latest unplugin version without that flag disabled?

Yes that works as well!

**Comment by userquin** [comment]
nice, we can finally close this issue 🥳

**Comment by BobbieGoede** [comment]
This should be resolved upstream now, refreshing your package lockfiles and installing should be sufficient to resolve this issue (no overrides needed).

We will publish a patch release in the coming days which will raise the compatible sub-dependency version, which should further ensure fix is included on install.

**Comment by jakubkoje** [comment]
Can confirm that sourcemaps are working again after recreating pnpm-lock.yaml. Thanks!

**Comment by ri-gr** [comment]
I can still reproduce the broken source-mapping with latest Nuxt "3.15.4" and i18n "9.2.0". If I remove the i18n module in my project mapping and debugging works. Can anybody from this thread confirm?

**Comment by BobbieGoede** [comment]
@ri-gr 
If you're still experiencing this with the latest versions, please provide a reproduction so we can take a look 🙏

You can open a new issue and reference this once.

**Comment by wJoenn** [comment]
Can confirm I still have the issue in our nuxt 3.15.4 app with @nuxtjs/i18n 9.2.1 installed
Disabling the `i18n.bundle.optimizeTranslationDirective` option in our `nuxt.config.ts` did the trick.
I'll try to cook a repro during the weekend if none have been given then

**Comment by gukandrew** [comment]
> Can confirm I still have the issue in our nuxt 3.15.4 app with @nuxtjs/i18n 9.2.1 installed Disabling the `i18n.bundle.optimizeTranslationDirective` option in our `nuxt.config.ts` did the trick. I'll try to cook a repro during the weekend if none have been given then

Unlike the case of using:
```json
"overrides": {
    "@intlify/unplugin-vue-i18n": "6.0.3"
  },
```

I can confirm the next config works:
```js
export default defineNuxtConfig({
  modules: [
    '@nuxtjs/i18n',
    // ...
  ],
  i18n: {
    bundle: {
      optimizeTranslationDirective: false,   //  <=== works
    },

  // ...
})
```
